### ISSUE TITLE
Investigate OT implementations we can provide for realtime Jupyter collaboration in dotscience

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/jupyterlab-plugin#5]
I’m currently investigating whether the existing https://github.com/jupyterlab/jupyterlab-google-drive plugin could be made to work against https://github.com/goodow/realtime-store which claims to support the Google Realtime API, as that would get us started.

Goal: write a design doc

- [ ] get realtime-server & realtime-playground into local stack
- [ ] get jupyter dev working locally on my mac
- [ ] add dotscience plugin
- [ ] add jupyterlab-google-drive plugin
- [ ] get jupyter pointing at realtime-server
- [ ] figure out how architecture will work when jupyter on the runner needs to talk to realtime stuff on dotscience cloud (maybe we never copy the workspace to the runner, but instead access it remotely via a drive-like API? or we only use realtime-server for coordination on in-memory state, and still write to the local filesystem?)
- [ ] figure out users & auth (identities from dotscience cloud should appear in the realtime presence in jupyter running on the runner)
- [ ] figure out sharing (does realtime-* have support for sharing settings or do we implement that ourselves in gateway for example?)

**Comment by Godley** [comment]
Canned ages ago in favour of git-style 🤷‍♀️
